export const SET_MOST_PLAYED_GAMES = 'SET_MOST_PLAYED_GAMES';
export const GET_MOST_PLAYED_GAMES = 'GET_MOST_PLAYED_GAMES';

export const SET_MOST_REVIEWED_GAMES = 'SET_MOST_REVIEWED_GAMES';
export const GET_MOST_REVIEWED_GAMES = 'GET_MOST_REVIEWED_GAMES'