export const SET_MOST_PLAYED_GAMES = 'SET_MOST_PLAYED_GAMES';
export const GET_MOST_PLAYED_GAMES = 'GET_MOST_PLAYED_GAMES';

export const SET_MOST_REVIEWED_GAMES = 'SET_MOST_REVIEWED_GAMES';
export const GET_MOST_REVIEWED_GAMES = 'GET_MOST_REVIEWED_GAMES';

export const SET_FUNNIEST_REVIEWS = 'SET_FUNNIEST_REVIEWS';
export const GET_FUNNIEST_REVIEWS = 'GET_FUNNIEST_REVIEWS';

export const SET_MOST_HELPFUL_REVIEWS = 'SET_MOST_HELPFUL_REVIEWS';
export const GET_MOST_HELPFUL_REVIEWS = 'GET_MOST_HELPFUL_REVIEWS';